[Service]
Restart=no
KillSignal=SIGTERM
KillMode=mixed
TimeoutStopSec=infinity
SendSIGKILL=no
ExecCondition=+/usr/bin/python3 -I /usr/local/lib/inkyos/test-access-activation.py --consume-helper-permit
